const STRATEGY_BUY = "STRATEGY_BUY";
const STRATEGY_SELL = "STRATEGY_SELL";
const STRATEGY_HOLD = "STRATEGY_HOLD";
const FIVE_BIG = "FIVEBIG";
const FIVE_SMALL = "FIVE_SMALL";
const FIVE_IDLE = "FIVE_IDLE";
const TRANSACTION_FEE = 0.00075;
const CANDLE_INTERVAL_MOVING_AVG = "1m";
const CANDLE_INTERVAL_AVG_DIFF = "1h";

module.exports = {
    STRATEGY_BUY: STRATEGY_BUY,
    STRATEGY_SELL: STRATEGY_SELL,
    STRATEGY_HOLD: STRATEGY_HOLD,
    FIVE_BIG: FIVE_BIG,
    FIVE_SMALL: FIVE_SMALL,
    FIVE_IDLE: FIVE_IDLE,
    TRANSACTION_FEE: TRANSACTION_FEE,
    CANDLE_INTERVAL_MOVING_AVG: CANDLE_INTERVAL_MOVING_AVG,
    CANDLE_INTERVAL_AVG_DIFF: CANDLE_INTERVAL_AVG_DIFF,
}