const STRATEGY_BUY = "STRATEGY_BUY";
const STRATEGY_SELL = "STRATEGY_SELL";
const STRATEGY_HOLD = "STRATEGY_HOLD";
const FIVE_BIG = "FIVEBIG";
const FIVE_SMALL = "FIVE_SMALL";
const FIVE_IDLE = "FIVE_IDLE"

module.exports = {
    STRATEGY_BUY: STRATEGY_BUY,
    STRATEGY_SELL: STRATEGY_SELL,
    STRATEGY_HOLD: STRATEGY_HOLD,
    FIVE_BIG: FIVE_BIG,
    FIVE_SMALL: FIVE_SMALL,
    FIVE_IDLE: FIVE_IDLE,
}